Kursach-Voenkomat/Controllers/RecordController.cs
using Kursach_Voenkomat.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Kursach_Voenkomat.Controllers
{
    public class RecordController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RecordController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.RecordModel != null ?
                         View(await _context.RecordModel.ToListAsync()) :
                         Problem("Entity set 'ApplicationDbContext.RecordModel'  is null.");
        }

        [HttpGet]
        public async Task<IActionResult> FilterByDate(DateTime? startDate, DateTime? endDate)
        {
            ViewBag.StartDate = startDate?.ToString("yyyy-MM-dd");
            ViewBag.EndDate = endDate?.ToString("yyyy-MM-dd");

            if (startDate != null && endDate != null)
            {
                var filteredRecords = await _context.RecordModel
                    .Where(record => record.Дата_посещения >= startDate && record.Дата_посещения <= endDate)
                    .ToListAsync();

                return View(nameof(Index), filteredRecords);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ReportByDay(DateTime? startDate, DateTime? endDate)
        {
            if (startDate != null && endDate != null)
            {
                var filteredRecords = await _context.RecordModel
                    .Where(record => record.Дата_посещения >= startDate && record.Дата_посещения <= endDate)
                    .ToListAsync();

                // Группировка записей по дням
                var dailyCounts = filteredRecords
                    .GroupBy(record => new { record.Дата_посещения.Year, record.Дата_посещения.Month, record.Дата_посещения.Day })
                    .Select(group => new { Day = new DateTime(group.Key.Year, group.Key.Month, group.Key.Day), Count = group.Count() })
                    .OrderBy(item => item.Day)
                    .ToList();

                // Создание данных для графика
                var days = dailyCounts.Select(item => item.Day.ToString("yyyy-MM-dd"));
                var counts = dailyCounts.Select(item => item.Count);

                ViewBag.Days = days;
                ViewBag.Counts = counts;

                return View("~/Views/Reports/ReportByDay.cshtml"); // Представление для отображения графика
            }

            else
            {
                var allRecords = await _context.RecordModel.ToListAsync();

                var dailyCounts = allRecords
                    .GroupBy(record => new { record.Дата_посещения.Year, record.Дата_посещения.Month, record.Дата_посещения.Day })
                    .Select(group => new { Day = new DateTime(group.Key.Year, group.Key.Month, group.Key.Day), Count = group.Count() })
                    .OrderBy(item => item.Day)
                    .ToList();

                var days = dailyCounts.Select(item => item.Day.ToString("yyyy-MM-dd"));
                var counts = dailyCounts.Select(item => item.Count);

                ViewBag.Days = days;
                ViewBag.Counts = counts;

                return View("~/Views/Reports/ReportByDay.cshtml"); // Представление для отображения графика
            }
        }

    }
}

Kursach-Voenkomat/Views/Record/Index.cshtml
@model IEnumerable<Kursach_Voenkomat.Models.RecordModel>

@{
    ViewData["Title"] = "Посещения";
}

<h1>Посещения</h1>

<form asp-controller="Record" asp-action="FilterByDate" method="get">
    <table border="0" cellspacing="5" cellpadding="5">
        <tbody>
            <tr>
                <td>Дата начала:</td>
                <td><input type="date" id="startDate" name="startDate" value="@ViewBag.StartDate"></td>
            </tr>
            <tr>
                <td>Дата окончания:</td>
                <td><input type="date" id="endDate" name="endDate" value="@ViewBag.EndDate"></td>
            </tr>
        </tbody>
    </table>
    <button type="submit" class="filtr-button">С фильтром</button>


    <a asp-controller="Record" asp-action="FilterByDate" class="non-filtr-button">Без фильтра</a>


    <a asp-controller="Record" asp-action="ReportByDay" asp-route-startDate="@ViewBag.StartDate" asp-route-endDate="@ViewBag.EndDate" class="graph-button">График</a>
</form>

<table id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Фамилия)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Имя)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Отчество)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Дата_рождения)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Дата_посещения)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Фамилия)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Имя)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Отчество)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Дата_рождения)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Дата_посещения)
                </td>
                <td>
                    <a asp-controller="Призывники" asp-action="Create" asp-route-id="@item.ID_посещения">Добавить призывника</a>
                </td>
            </tr>
        }
    </tbody>
</table>